# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QDockWidget, QHBoxLayout,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QProgressBar, QSizePolicy,
    QStatusBar, QTabWidget, QToolBar, QTreeView,
    QVBoxLayout, QWidget)
from pastrocore.gui import rc_icons  # noqa: F401
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1119, 721)
        icon = QIcon()
        icon.addFile(u":/icons/pAstroCORE_icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.actionNewProject = QAction(MainWindow)
        self.actionNewProject.setObjectName(u"actionNewProject")
        icon1 = QIcon()
        icon1.addFile(u":/icons/new_project.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionNewProject.setIcon(icon1)
        self.actionOpenProject = QAction(MainWindow)
        self.actionOpenProject.setObjectName(u"actionOpenProject")
        icon2 = QIcon()
        icon2.addFile(u":/icons/open_project_icon.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpenProject.setIcon(icon2)
        self.actionSaveProject = QAction(MainWindow)
        self.actionSaveProject.setObjectName(u"actionSaveProject")
        icon3 = QIcon()
        icon3.addFile(u":/icons/save_project_icon.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSaveProject.setIcon(icon3)
        self.actionOpen_Package = QAction(MainWindow)
        self.actionOpen_Package.setObjectName(u"actionOpen_Package")
        icon4 = QIcon()
        icon4.addFile(u":/icons/package_import.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpen_Package.setIcon(icon4)
        self.actionPackage_Project = QAction(MainWindow)
        self.actionPackage_Project.setObjectName(u"actionPackage_Project")
        icon5 = QIcon()
        icon5.addFile(u":/icons/package_export.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPackage_Project.setIcon(icon5)
        self.actionExport_VEX = QAction(MainWindow)
        self.actionExport_VEX.setObjectName(u"actionExport_VEX")
        icon6 = QIcon()
        icon6.addFile(u":/icons/export_icon.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExport_VEX.setIcon(icon6)
        self.actionImport_VEX = QAction(MainWindow)
        self.actionImport_VEX.setObjectName(u"actionImport_VEX")
        icon7 = QIcon()
        icon7.addFile(u":/icons/import_icon.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionImport_VEX.setIcon(icon7)
        self.actionImport_CFX = QAction(MainWindow)
        self.actionImport_CFX.setObjectName(u"actionImport_CFX")
        icon8 = QIcon()
        icon8.addFile(u":/icons/cfx_import.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionImport_CFX.setIcon(icon8)
        self.actionExport_CFX = QAction(MainWindow)
        self.actionExport_CFX.setObjectName(u"actionExport_CFX")
        icon9 = QIcon()
        icon9.addFile(u":/icons/cfx_export.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExport_CFX.setIcon(icon9)
        self.actionAnalysis = QAction(MainWindow)
        self.actionAnalysis.setObjectName(u"actionAnalysis")
        icon10 = QIcon()
        icon10.addFile(u":/icons/analyze.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAnalysis.setIcon(icon10)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        icon11 = QIcon()
        icon11.addFile(u":/icons/exit_icon.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExit.setIcon(icon11)
        self.actionExit.setMenuRole(QAction.MenuRole.QuitRole)
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        icon12 = QIcon()
        icon12.addFile(u":/icons/preferences.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPreferences.setIcon(icon12)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon13 = QIcon()
        icon13.addFile(u":/icons/about_icon.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAbout.setIcon(icon13)
        self.actionProject_Explorer = QAction(MainWindow)
        self.actionProject_Explorer.setObjectName(u"actionProject_Explorer")
        icon14 = QIcon()
        icon14.addFile(u":/icons/explorer.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionProject_Explorer.setIcon(icon14)
        self.actionProject_Explorer.setCheckable(True)
        self.actionProject_Explorer.setChecked(True)
        self.actionSource_Catalog_Manager = QAction(MainWindow)
        self.actionSource_Catalog_Manager.setObjectName(u"actionSource_Catalog_Manager")
        icon15 = QIcon()
        icon15.addFile(u":/icons/catalog_sources.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSource_Catalog_Manager.setIcon(icon15)
        self.actionTelescope_Catalog_Manager = QAction(MainWindow)
        self.actionTelescope_Catalog_Manager.setObjectName(u"actionTelescope_Catalog_Manager")
        icon16 = QIcon()
        icon16.addFile(u":/icons/catalog_telescopes.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionTelescope_Catalog_Manager.setIcon(icon16)
        self.actionSave_Project_As = QAction(MainWindow)
        self.actionSave_Project_As.setObjectName(u"actionSave_Project_As")
        icon17 = QIcon()
        icon17.addFile(u":/icons/save_project_as_icon.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSave_Project_As.setIcon(icon17)
        self.actionImport_Observation = QAction(MainWindow)
        self.actionImport_Observation.setObjectName(u"actionImport_Observation")
        icon18 = QIcon()
        icon18.addFile(u":/icons/observation_import.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionImport_Observation.setIcon(icon18)
        self.actionExport_Observation = QAction(MainWindow)
        self.actionExport_Observation.setObjectName(u"actionExport_Observation")
        icon19 = QIcon()
        icon19.addFile(u":/icons/observation_export.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExport_Observation.setIcon(icon19)
        self.actionCalculate = QAction(MainWindow)
        self.actionCalculate.setObjectName(u"actionCalculate")
        icon20 = QIcon()
        icon20.addFile(u":/icons/calculate.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCalculate.setIcon(icon20)
        self.actionVisualize = QAction(MainWindow)
        self.actionVisualize.setObjectName(u"actionVisualize")
        icon21 = QIcon()
        icon21.addFile(u":/icons/visualize.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionVisualize.setIcon(icon21)
        self.actionSession = QAction(MainWindow)
        self.actionSession.setObjectName(u"actionSession")
        icon22 = QIcon()
        icon22.addFile(u":/icons/session.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSession.setIcon(icon22)
        self.actionLast_Run_Report = QAction(MainWindow)
        self.actionLast_Run_Report.setObjectName(u"actionLast_Run_Report")
        icon23 = QIcon()
        icon23.addFile(u":/icons/report.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionLast_Run_Report.setIcon(icon23)
        self.actionLast_Run_Report.setEnabled(False)
        self.actionGenerate_Observations = QAction(MainWindow)
        self.actionGenerate_Observations.setObjectName(u"actionGenerate_Observations")
        icon24 = QIcon()
        icon24.addFile(u":/icons/generate.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionGenerate_Observations.setIcon(icon24)
        self.actionExport_Calulcated_Data = QAction(MainWindow)
        self.actionExport_Calulcated_Data.setObjectName(u"actionExport_Calulcated_Data")
        icon25 = QIcon()
        icon25.addFile(u":/icons/data_export.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExport_Calulcated_Data.setIcon(icon25)
        self.mainCentralWidget = QWidget(MainWindow)
        self.mainCentralWidget.setObjectName(u"mainCentralWidget")
        self.mainLayout = QHBoxLayout(self.mainCentralWidget)
        self.mainLayout.setObjectName(u"mainLayout")
        self.tabContainer = QTabWidget(self.mainCentralWidget)
        self.tabContainer.setObjectName(u"tabContainer")
        self.tabContainer.setTabShape(QTabWidget.TabShape.Rounded)
        self.tabContainer.setElideMode(Qt.TextElideMode.ElideNone)
        self.tabContainer.setTabsClosable(True)
        self.tabContainer.setMovable(True)
        self.tabWelcome = QWidget()
        self.tabWelcome.setObjectName(u"tabWelcome")
        self.welcomeLayout = QVBoxLayout(self.tabWelcome)
        self.welcomeLayout.setObjectName(u"welcomeLayout")
        self.label = QLabel(self.tabWelcome)
        self.label.setObjectName(u"label")
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.welcomeLayout.addWidget(self.label)

        self.tabContainer.addTab(self.tabWelcome, "")

        self.mainLayout.addWidget(self.tabContainer)

        MainWindow.setCentralWidget(self.mainCentralWidget)
        self.mainMenuBar = QMenuBar(MainWindow)
        self.mainMenuBar.setObjectName(u"mainMenuBar")
        self.mainMenuBar.setGeometry(QRect(0, 0, 1119, 22))
        self.mainMenuBar.setNativeMenuBar(False)
        self.menuFile = QMenu(self.mainMenuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuFile.setTearOffEnabled(False)
        self.menuRecent_Projects = QMenu(self.menuFile)
        self.menuRecent_Projects.setObjectName(u"menuRecent_Projects")
        self.menuImport_Schedule = QMenu(self.menuFile)
        self.menuImport_Schedule.setObjectName(u"menuImport_Schedule")
        self.menuExport_Schedule = QMenu(self.menuFile)
        self.menuExport_Schedule.setObjectName(u"menuExport_Schedule")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuExport_Schedule.sizePolicy().hasHeightForWidth())
        self.menuExport_Schedule.setSizePolicy(sizePolicy)
        self.menuExport_Schedule.setIcon(icon6)
        self.menuOptions = QMenu(self.mainMenuBar)
        self.menuOptions.setObjectName(u"menuOptions")
        self.menuHelp = QMenu(self.mainMenuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuHelp.setMouseTracking(True)
        self.menuHelp.setAutoFillBackground(False)
        self.menuWindow = QMenu(self.mainMenuBar)
        self.menuWindow.setObjectName(u"menuWindow")
        self.menuTools = QMenu(self.mainMenuBar)
        self.menuTools.setObjectName(u"menuTools")
        MainWindow.setMenuBar(self.mainMenuBar)
        self.mainStatusBar = QStatusBar(MainWindow)
        self.mainStatusBar.setObjectName(u"mainStatusBar")
        self.mainStatusBar.setAutoFillBackground(False)
        self.progressBar = QProgressBar(self.mainStatusBar)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(0, 0, 100, 16))
        self.progressBar.setMaximumSize(QSize(200, 16))
        self.progressBar.setVisible(False)
        self.progressBar.setValue(0)
        MainWindow.setStatusBar(self.mainStatusBar)
        self.mainToolBar = QToolBar(MainWindow)
        self.mainToolBar.setObjectName(u"mainToolBar")
        self.mainToolBar.setMovable(False)
        self.mainToolBar.setIconSize(QSize(24, 24))
        self.mainToolBar.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.mainToolBar)
        self.dockWidget = QDockWidget(MainWindow)
        self.dockWidget.setObjectName(u"dockWidget")
        self.dockWidget.setContextMenuPolicy(Qt.ContextMenuPolicy.PreventContextMenu)
        self.dockWidget.setFloating(False)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.explorerLayout = QVBoxLayout(self.dockWidgetContents)
        self.explorerLayout.setSpacing(6)
        self.explorerLayout.setObjectName(u"explorerLayout")
        self.explorerFilter = QLineEdit(self.dockWidgetContents)
        self.explorerFilter.setObjectName(u"explorerFilter")
        self.explorerFilter.setClearButtonEnabled(True)

        self.explorerLayout.addWidget(self.explorerFilter)

        self.projectExplorer = QTreeView(self.dockWidgetContents)
        self.projectExplorer.setObjectName(u"projectExplorer")
        self.projectExplorer.setMinimumSize(QSize(220, 0))
        self.projectExplorer.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.projectExplorer.setHeaderHidden(True)
        self.projectExplorer.header().setVisible(False)

        self.explorerLayout.addWidget(self.projectExplorer)

        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dockWidget)

        self.mainMenuBar.addAction(self.menuFile.menuAction())
        self.mainMenuBar.addAction(self.menuTools.menuAction())
        self.mainMenuBar.addAction(self.menuOptions.menuAction())
        self.mainMenuBar.addAction(self.menuWindow.menuAction())
        self.mainMenuBar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNewProject)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpenProject)
        self.menuFile.addAction(self.menuRecent_Projects.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSaveProject)
        self.menuFile.addAction(self.actionSave_Project_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_Calulcated_Data)
        self.menuFile.addAction(self.menuExport_Schedule.menuAction())
        self.menuFile.addAction(self.menuImport_Schedule.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_Package)
        self.menuFile.addAction(self.actionPackage_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuImport_Schedule.addAction(self.actionImport_VEX)
        self.menuImport_Schedule.addAction(self.actionImport_CFX)
        self.menuExport_Schedule.addAction(self.actionExport_VEX)
        self.menuExport_Schedule.addAction(self.actionExport_CFX)
        self.menuOptions.addAction(self.actionPreferences)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionSource_Catalog_Manager)
        self.menuOptions.addAction(self.actionTelescope_Catalog_Manager)
        self.menuHelp.addAction(self.actionAbout)
        self.menuWindow.addAction(self.actionProject_Explorer)
        self.menuTools.addAction(self.actionCalculate)
        self.menuTools.addAction(self.actionLast_Run_Report)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionVisualize)
        self.menuTools.addAction(self.actionAnalysis)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionGenerate_Observations)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionSession)
        self.mainToolBar.addAction(self.actionNewProject)
        self.mainToolBar.addAction(self.actionOpenProject)
        self.mainToolBar.addAction(self.actionSaveProject)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionImport_VEX)
        self.mainToolBar.addAction(self.actionExport_VEX)
        self.mainToolBar.addAction(self.actionExport_Calulcated_Data)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionCalculate)
        self.mainToolBar.addAction(self.actionVisualize)
        self.mainToolBar.addAction(self.actionAnalysis)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionGenerate_Observations)
        self.mainToolBar.addAction(self.actionSession)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionPreferences)

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        self.actionProject_Explorer.toggled.connect(self.dockWidget.setVisible)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"pAstroCORE", None))
#if QT_CONFIG(shortcut)
        self.actionNewProject.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionNewProject.setText(QCoreApplication.translate("MainWindow", u"New Project", None))
        self.actionNewProject.setIconText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(shortcut)
        self.actionOpenProject.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenProject.setText(QCoreApplication.translate("MainWindow", u"Open Project", None))
        self.actionOpenProject.setIconText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(shortcut)
        self.actionSaveProject.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSaveProject.setText(QCoreApplication.translate("MainWindow", u"Save Project", None))
        self.actionSaveProject.setIconText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionOpen_Package.setText(QCoreApplication.translate("MainWindow", u"Import Project", None))
#if QT_CONFIG(tooltip)
        self.actionOpen_Package.setToolTip(QCoreApplication.translate("MainWindow", u"Open a project someone sent as one file", None))
#endif // QT_CONFIG(tooltip)
        self.actionPackage_Project.setText(QCoreApplication.translate("MainWindow", u"Export Project", None))
#if QT_CONFIG(tooltip)
        self.actionPackage_Project.setToolTip(QCoreApplication.translate("MainWindow", u"Pack this project into one file, to send or to attach to a bug report", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionExport_VEX.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionExport_VEX.setText(QCoreApplication.translate("MainWindow", u"VEX...", None))
#if QT_CONFIG(tooltip)
        self.actionExport_VEX.setToolTip(QCoreApplication.translate("MainWindow", u"Write this observation as a VEX file. Blocks describing station hardware are written empty, and named afterwards", None))
#endif // QT_CONFIG(tooltip)
        self.actionExport_VEX.setIconText(QCoreApplication.translate("MainWindow", u"Export VEX", None))
#if QT_CONFIG(shortcut)
        self.actionImport_VEX.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionImport_VEX.setText(QCoreApplication.translate("MainWindow", u"VEX...", None))
#if QT_CONFIG(tooltip)
        self.actionImport_VEX.setToolTip(QCoreApplication.translate("MainWindow", u"Read a VEX file into this project as a new observation", None))
#endif // QT_CONFIG(tooltip)
        self.actionImport_VEX.setIconText(QCoreApplication.translate("MainWindow", u"Import VEX", None))
        self.actionImport_CFX.setText(QCoreApplication.translate("MainWindow", u"CFX...", None))
#if QT_CONFIG(tooltip)
        self.actionImport_CFX.setToolTip(QCoreApplication.translate("MainWindow", u"Read a CFX file into this project as a new observation", None))
#endif // QT_CONFIG(tooltip)
        self.actionExport_CFX.setText(QCoreApplication.translate("MainWindow", u"CFX...", None))
#if QT_CONFIG(tooltip)
        self.actionExport_CFX.setToolTip(QCoreApplication.translate("MainWindow", u"Write this observation as a CFX file for the ASC correlator. A space telescope is an ordinary station here. One file per frequency setup", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionAnalysis.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+A", None))
#endif // QT_CONFIG(shortcut)
        self.actionAnalysis.setText(QCoreApplication.translate("MainWindow", u"Analyze", None))
#if QT_CONFIG(tooltip)
        self.actionAnalysis.setToolTip(QCoreApplication.translate("MainWindow", u"Analyze", None))
#endif // QT_CONFIG(tooltip)
        self.actionAnalysis.setIconText(QCoreApplication.translate("MainWindow", u"Analysis", None))
#if QT_CONFIG(shortcut)
        self.actionExit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
#if QT_CONFIG(shortcut)
        self.actionPreferences.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+,", None))
#endif // QT_CONFIG(shortcut)
        self.actionPreferences.setText(QCoreApplication.translate("MainWindow", u"Preferences...", None))
        self.actionPreferences.setIconText(QCoreApplication.translate("MainWindow", u"Settings", None))
#if QT_CONFIG(shortcut)
        self.actionAbout.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
#if QT_CONFIG(shortcut)
        self.actionProject_Explorer.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+B", None))
#endif // QT_CONFIG(shortcut)
        self.actionProject_Explorer.setText(QCoreApplication.translate("MainWindow", u"Project Explorer", None))
        self.actionSource_Catalog_Manager.setText(QCoreApplication.translate("MainWindow", u"Source Catalog Browser", None))
        self.actionTelescope_Catalog_Manager.setText(QCoreApplication.translate("MainWindow", u"Telescope Catalog Browser", None))
#if QT_CONFIG(shortcut)
        self.actionSave_Project_As.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_Project_As.setText(QCoreApplication.translate("MainWindow", u"Save Project As...", None))
        self.actionImport_Observation.setText(QCoreApplication.translate("MainWindow", u"Import Observation", None))
        self.actionExport_Observation.setText(QCoreApplication.translate("MainWindow", u"Export Observation", None))
#if QT_CONFIG(shortcut)
        self.actionCalculate.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionCalculate.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.actionCalculate.setIconText(QCoreApplication.translate("MainWindow", u"Calculate", None))
#if QT_CONFIG(shortcut)
        self.actionVisualize.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionVisualize.setText(QCoreApplication.translate("MainWindow", u"Visualize", None))
        self.actionVisualize.setIconText(QCoreApplication.translate("MainWindow", u"Plots", None))
#if QT_CONFIG(shortcut)
        self.actionSession.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+J", None))
#endif // QT_CONFIG(shortcut)
        self.actionSession.setText(QCoreApplication.translate("MainWindow", u"Session Viewer", None))
#if QT_CONFIG(tooltip)
        self.actionSession.setToolTip(QCoreApplication.translate("MainWindow", u"Session Viewer", None))
#endif // QT_CONFIG(tooltip)
        self.actionSession.setIconText(QCoreApplication.translate("MainWindow", u"Session", None))
#if QT_CONFIG(shortcut)
        self.actionLast_Run_Report.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionLast_Run_Report.setText(QCoreApplication.translate("MainWindow", u"Calculations Report", None))
#if QT_CONFIG(tooltip)
        self.actionLast_Run_Report.setToolTip(QCoreApplication.translate("MainWindow", u"Calculations Report", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionGenerate_Observations.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+G", None))
#endif // QT_CONFIG(shortcut)
        self.actionGenerate_Observations.setText(QCoreApplication.translate("MainWindow", u"Generate Observations", None))
        self.actionGenerate_Observations.setIconText(QCoreApplication.translate("MainWindow", u"Generate", None))
#if QT_CONFIG(shortcut)
        self.actionExport_Calulcated_Data.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionExport_Calulcated_Data.setText(QCoreApplication.translate("MainWindow", u"Export Calculated Data", None))
        self.actionExport_Calulcated_Data.setIconText(QCoreApplication.translate("MainWindow", u"Results", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Select item from Project Explorer.", None))
        self.tabContainer.setTabText(self.tabContainer.indexOf(self.tabWelcome), QCoreApplication.translate("MainWindow", u"Welcome", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuRecent_Projects.setTitle(QCoreApplication.translate("MainWindow", u"Recent Projects", None))
#if QT_CONFIG(tooltip)
        self.menuRecent_Projects.setToolTip(QCoreApplication.translate("MainWindow", u"Projects opened before, most recent first", None))
#endif // QT_CONFIG(tooltip)
        self.menuImport_Schedule.setTitle(QCoreApplication.translate("MainWindow", u"Import Schedule", None))
#if QT_CONFIG(tooltip)
        self.menuImport_Schedule.setToolTip(QCoreApplication.translate("MainWindow", u"Read a schedule somebody else wrote. What this model cannot hold is named rather than carried", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.menuExport_Schedule.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.menuExport_Schedule.setTitle(QCoreApplication.translate("MainWindow", u"Export Observations", None))
        self.menuOptions.setTitle(QCoreApplication.translate("MainWindow", u"Options", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuWindow.setTitle(QCoreApplication.translate("MainWindow", u"Window", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.mainToolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"Main", None))
        self.dockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Project Explorer", None))
        self.explorerFilter.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Filter observations...", None))
#if QT_CONFIG(tooltip)
        self.explorerFilter.setToolTip(QCoreApplication.translate("MainWindow", u"Show only the observations whose code contains this.", None))
#endif // QT_CONFIG(tooltip)
    # retranslateUi

